### ISSUE TITLE
Require recursive-open-struct

### ISSUE THREAD

**Issue by danigonza** [rogercampos/toqua#1]
I have this error when the gem is added to the project:
```
/home/daniel/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/toqua-0.1.1/lib/toqua/search.rb:1:in `require': cannot load such file -- recursive-open-struct (LoadError)
```

In the search class, there is a `require 'recursive-open-struct'` but the gem does not require it in the `Gemfile`. Should it be there, no?

**Comment by rogercampos** [comment]
yes, it's stated in the readme that you need that gem if you're using search. It's not a gem dependency because it's only necessary for searching.
